<?php
?>
<!DOCTYPE html>
<html>
<head>
    <title>Statement of Credits</title>
    <link rel="stylesheet" href="/~s2845297/B290295_website/frontend/assets/css/style.css">
</head>
<body>

<?php include __DIR__ . '/../components/header.php'; ?>

<div class="page-container">
    <h2>Statement of Credits</h2>

    <a href="/~s2845297/B290295_website/index.php" class="back-button">
        ← Back to Home
    </a>

    <br><br>

    <div class="card">
        <h3><strong>(a) Code sources and external resources used:</strong></h3>

        <p><strong>PHP PDO</strong><br>
        Source: <a href="https://www.php.net/manual/en/book.pdo.php" target="_blank">https://www.php.net/manual/en/book.pdo.php</a><br>
        In this project, PDO is used to connect to a MySQL database. It is used to perform parameterised queries on proteins, store protein search records, store analysis history, and store the results returned by the example dataset.
        </p>

        <p><strong>Chart.js</strong><br>
        Source: <a href="https://www.chartjs.org/" target="_blank">https://www.chartjs.org/</a><br>
        In this project, Chart.js is used to display MSA conservation plots, and the retrieved motif information is combined with conservation data to generate intuitive visualisations.
        </p>

        <p><strong>Biopython (Entrez module)</strong><br>
        Source: <a href="https://biopython.org/" target="_blank">https://biopython.org/</a><br>
        Used in <code>fetch_protein.py</code> to query the NCBI protein database. After the user defines a taxonomic group and protein name, a standardised query is performed to retrieve matching records and download protein sequences in FASTA format.
        </p>

        <p><strong>NCBI Entrez Programming Tools (E-utilities)</strong><br>
        Documentation: <a href="https://www.ncbi.nlm.nih.gov/books/NBK179288/" target="_blank">https://www.ncbi.nlm.nih.gov/books/NBK179288/</a><br>
        Uses an API key obtained from the NCBI database to prevent search requests from reaching the limit.
        </p>

        <p><strong>Clustal Omega</strong><br>
        Source: <a href="https://www.clustal.org/omega/" target="_blank">https://www.clustal.org/omega/</a><br>
        The backend script msa.py utilises this functionality to generate multiple sequence alignment (MSA) files, providing input data for subsequent phylogenetic tree construction.
        </p>

        <p><strong>Biopython (AlignIO module)</strong><br>
        Source: <a href="https://biopython.org/docs/latest/api/Bio.AlignIO.html" target="_blank">https://biopython.org/docs/latest/api/Bio.AlignIO.html</a><br>
        Used in msa.py to parse alignment files generated by Clustal Omega. It supports column-wise analysis of aligned sequences and is used to calculate conservation scores based on the frequency of residues in each alignment column.
        </p>

        <p><strong>Biopython (Phylo and TreeConstruction modules)</strong><br>
        Source: <a href="https://biopython.org/docs/latest/api/Bio.Phylo.html" target="_blank">https://biopython.org/docs/latest/api/Bio.Phylo.html</a><br>
        In tree.py, Biopython is used to calculate pairwise distances between sequences, construct phylogenetic trees using the agglomerative method, and export the trees to Newick format.
        </p>

        <p><strong>Matplotlib</strong><br>
        Source: <a href="https://matplotlib.org/" target="_blank">https://matplotlib.org/</a><br>
        Generate PNG images of the phylogenetic tree within <code>tree.py</code>. These images will subsequently be displayed in the web interface and provide files for users to export images.
        </p>

        <p><strong>PROSITE database</strong><br>
        Source: <a href="https://prosite.expasy.org/" target="_blank">https://prosite.expasy.org/</a><br>
        Utilise this website as the data source for motif analysis. The script <code>prosite_scan.py</code> uses simplified motif patterns to scan protein sequences and identify functional regions.
        </p>

        <p>
        Refer to the PHP manual: <a href="https://www.php.net/manual/en/" target="_blank">https://www.php.net/manual/en/</a>, 
        and the Biopython documentation: <a href="https://biopython.org/wiki/Documentation" target="_blank">https://biopython.org/wiki/Documentation</a>, 
        and adapt them to suit the specific requirements of this project.
        </p>
    </div>

    <br>

    <div class="card">
        <h3><strong>(b) AI tools used and exact usage:</strong></h3>

        <p>
        During the generation of this website, I used <strong>ChatGPT</strong> as a programming and debugging assistant to carry out the following 3 specific tasks:
        </p>

        <p>
        <strong>1. Debugging and visual enhancement of PHP scripts with basic functionality, including:</strong><br>
        Dividing the multiple sequence alignment (MSA) into two main sections—left and right—and adding NCBI hyperlinks for selected proteins<br>
        On the motif analysis page, displaying motif visualisation alongside conservation curves and adding dynamic effects to motifs
        </p>

        <p>
        <strong>2. Assisting in the development and debugging of backend Python scripts:</strong><br>
        Conservation score visualisation section (msa.py)<br>
        Motif scanning and visualisation section (prosite_scan.py)
        </p>

        <p>
        <strong>3. Assisting in the integration of frontend and backend components to create a polished website, for example:</strong><br>
        Resolving issues where results could not be passed between different functionalities due to inconsistent variable naming<br>
        Resolve formatting and display issues during Newick tree visualisation<br>
        Render charts in the corresponding reports generated by MSA and PROSITE scan
        </p>

        <p>
        All OpenAI-generated scripts and structures have been reviewed and modified by me, then organised and merged into the final website submitted
        </p>
    </div>

</div>

</body>
</html>
