<?php ob_start(); ?>
<?php
$content = ob_get_clean();
include __DIR__ . '/../layout.php';
?>

<div class="page-container">
<a href="/~s2845297/B290295_website/index.php" class="back-button">
        ← Back to Home
    </a>

    <br><br>

    <h2>Help / Biological Context</h2>

    <h3>Overview</h3>
    <div class="card">
        <p>
            This website enables users to search for user-defined taxa and specific protein sets, retrieve protein sequences, perform conservation analyses and conduct further motif scan research, thereby providing deeper insights into the core functions and evolution of proteins.
        </p>
    </div>

    <h3>Protein Sequence Comparison</h3>
    <div class="card">
        <p>
            Protein sequences are obtained from related species as co-origin proteins; by aligning these sequences, the conservation or diversity of protein functions across different species can be identified.
        </p>
    </div>

    <h3>Multiple Sequence Alignment (MSA)</h3>
    <div class="card">
        <p>
            MSA aligns sequences to enable direct comparison of amino acid sites and, through the display of BLOSUM62 conservation scores, identifies conserved regions, insertions and deletions. These conserved regions typically play a significant role in structural stability and biological function.
        </p>
    </div>

    <h3>Motif Analysis</h3>
    <div class="card">
        <p>
            Motif analysis identifies short sequences associated with specific biological functions; on this platform, this is combined with conservation scores to further highlight domains that may represent important functions.
        </p>
    </div>

    <h3>Phylogenetic Analysis</h3>
    <div class="card">
        <p>
            The alignment files generated by MSA are utilised to infer evolutionary relationships, construct phylogenetic trees, and illustrate the phylogenetic relationships between proteins from different species, thereby identifying closely related species groups and lineages with a high degree of divergence.
        </p>
    </div>

</div>
